import type { Ad, Product } from './types';

export const initialAds: Ad[] = [
  {
    id: 'ad1',
    brand: 'NexaGear',
    brandLogo: '/logos/nexagear.svg',
    thumbnail: 'https://picsum.photos/400/300',
    dataAiHint: 'running shoes',
    title: 'NexaGear Pro-Run: Defy Limits',
    description: 'Experience the ultimate in running technology. Lightweight, responsive, and durable.',
    category: 'Sports',
    viewedDate: '2024-07-20',
  },
  {
    id: 'ad2',
    brand: 'ChronoWatch',
    brandLogo: '/logos/chronowatch.svg',
    thumbnail: 'https://picsum.photos/400/300',
    dataAiHint: 'luxury watch',
    title: 'ChronoWatch Apex: Timeless Elegance',
    description: 'A masterpiece of precision engineering and classic design. Perfect for any occasion.',
    category: 'Fashion',
    viewedDate: '2024-07-19',
  },
  {
    id: 'ad3',
    brand: 'PixelPerfect',
    brandLogo: '/logos/pixelperfect.svg',
    thumbnail: 'https://picsum.photos/400/300',
    dataAiHint: 'camera lens',
    title: 'PixelPerfect X1: Capture Your World',
    description: 'Professional-grade camera for stunning photos and 4K video. Unleash your creativity.',
    category: 'Electronics',
    viewedDate: '2024-07-19',
  },
  {
    id: 'ad4',
    brand: 'HomeComfort',
    brandLogo: '/logos/homecomfort.svg',
    thumbnail: 'https://picsum.photos/400/300',
    dataAiHint: 'smart thermostat',
    title: 'HomeComfort Smart Thermostat',
    description: 'Save energy and stay comfortable with our AI-powered smart thermostat. Control from anywhere.',
    category: 'Home Goods',
    viewedDate: '2024-07-18',
  },
  {
    id: 'ad5',
    brand: 'GourmetGrind',
    brandLogo: '/logos/gourmetgrind.svg',
    thumbnail: 'https://picsum.photos/400/300',
    dataAiHint: 'coffee beans',
    title: 'GourmetGrind Organic Coffee Beans',
    description: 'Sustainably sourced, single-origin beans for the perfect cup of coffee, every time.',
    category: 'Groceries',
    viewedDate: '2024-07-17',
  },
    {
    id: 'ad6',
    brand: 'SoundWave',
    brandLogo: '/logos/soundwave.svg',
    thumbnail: 'https://picsum.photos/400/300',
    dataAiHint: 'wireless headphones',
    title: 'SoundWave Freedom: Cut the Cords',
    description: 'Immersive sound, all-day comfort, and crystal-clear calls. The last pair of headphones you\'ll need.',
    category: 'Electronics',
    viewedDate: '2024-07-16',
  },
];

export const initialProducts: Product[] = initialAds.map((ad, index) => ({
  ...ad,
  price: parseFloat((Math.random() * (300 - 20) + 20).toFixed(2)),
  commissionRate: parseFloat((Math.random() * (0.15 - 0.02) + 0.02).toFixed(2)),
}));
